"""
MSE-2 House Price Prediction — Streamlit App
=============================================
Run with:
    streamlit run app.py

Requires: champion_model.pkl and scaler.pkl in the same directory.
Generated by pipeline.py (MSE_2_ANN environment).
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
import os

# ── Page config ────────────────────────────────────────────────────
st.set_page_config(
    page_title="House Price Predictor",
    page_icon="🏠",
    layout="centered",
    initial_sidebar_state="collapsed",
)

# ── Custom CSS ─────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
}

.main {
    background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
    min-height: 100vh;
}

.stApp {
    background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%);
}

/* Hero card */
.hero-card {
    background: rgba(255,255,255,0.05);
    backdrop-filter: blur(20px);
    -webkit-backdrop-filter: blur(20px);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 24px;
    padding: 2.5rem 3rem;
    margin-bottom: 2rem;
    text-align: center;
    box-shadow: 0 8px 32px rgba(0,0,0,0.3);
}

.hero-title {
    font-size: 2.6rem;
    font-weight: 700;
    background: linear-gradient(90deg, #a78bfa, #60a5fa, #34d399);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    margin-bottom: 0.5rem;
    line-height: 1.2;
}

.hero-sub {
    font-size: 1rem;
    color: rgba(255,255,255,0.55);
    font-weight: 400;
    margin-top: 0.4rem;
}

/* Section labels */
.section-label {
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #a78bfa;
    margin-bottom: 0.8rem;
    margin-top: 1.6rem;
}

/* Prediction result card */
.result-card {
    background: linear-gradient(135deg, rgba(167,139,250,0.15), rgba(96,165,250,0.15));
    border: 1px solid rgba(167,139,250,0.35);
    border-radius: 20px;
    padding: 2rem 2.5rem;
    text-align: center;
    margin-top: 1.5rem;
    box-shadow: 0 4px 24px rgba(167,139,250,0.15);
    animation: fadeIn 0.5s ease;
}

.result-label {
    font-size: 0.8rem;
    font-weight: 600;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: rgba(255,255,255,0.5);
    margin-bottom: 0.5rem;
}

.result-price {
    font-size: 3.2rem;
    font-weight: 700;
    background: linear-gradient(90deg, #a78bfa, #60a5fa);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    letter-spacing: -0.02em;
    line-height: 1.1;
}

.result-meta {
    font-size: 0.82rem;
    color: rgba(255,255,255,0.4);
    margin-top: 0.6rem;
}

/* Metric pills */
.metric-row {
    display: flex;
    gap: 0.75rem;
    justify-content: center;
    margin-top: 1.2rem;
    flex-wrap: wrap;
}

.metric-pill {
    background: rgba(255,255,255,0.07);
    border: 1px solid rgba(255,255,255,0.12);
    border-radius: 50px;
    padding: 0.35rem 0.9rem;
    font-size: 0.78rem;
    color: rgba(255,255,255,0.65);
    font-weight: 500;
}

/* Input styling */
div[data-testid="stSlider"] > div > div {
    background: rgba(167,139,250,0.3) !important;
}

div[data-testid="stSelectbox"] label,
div[data-testid="stSlider"] label {
    color: rgba(255,255,255,0.75) !important;
    font-size: 0.9rem !important;
    font-weight: 500 !important;
}

/* Button */
div[data-testid="stButton"] > button {
    background: linear-gradient(135deg, #7c3aed, #2563eb);
    color: white;
    border: none;
    border-radius: 12px;
    padding: 0.75rem 2rem;
    font-size: 1rem;
    font-weight: 600;
    width: 100%;
    cursor: pointer;
    transition: all 0.2s ease;
    letter-spacing: 0.02em;
    margin-top: 1rem;
}

div[data-testid="stButton"] > button:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 24px rgba(124,58,237,0.4);
}

/* Info box */
.info-box {
    background: rgba(52, 211, 153, 0.08);
    border: 1px solid rgba(52, 211, 153, 0.25);
    border-radius: 12px;
    padding: 1rem 1.2rem;
    font-size: 0.83rem;
    color: rgba(255,255,255,0.6);
    margin-top: 1rem;
    line-height: 1.6;
}

.info-box b { color: #34d399; }

/* Hide streamlit branding */
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(12px); }
    to   { opacity: 1; transform: translateY(0); }
}
</style>
""", unsafe_allow_html=True)

# ── Load model ─────────────────────────────────────────────────────
@st.cache_resource
def load_artifacts():
    base = os.path.dirname(__file__)
    model  = joblib.load(os.path.join(base, "champion_model.pkl"))
    scaler = joblib.load(os.path.join(base, "scaler.pkl"))
    return model, scaler

try:
    model, scaler = load_artifacts()
    model_loaded = True
except FileNotFoundError:
    model_loaded = False

# The 7 features in the exact order the model expects
FEATURE_COLS = [
    "area_sqft", "rooms", "age_years",
    "dist_city_km", "garage", "log_area", "age_bucket"
]

# ── Hero ───────────────────────────────────────────────────────────
st.markdown("""
<div class="hero-card">
    <div class="hero-title">🏠 House Price Predictor</div>
    <div class="hero-sub">
        MSE-2 · Linear Regression · Trained on 745 cleaned samples
    </div>
</div>
""", unsafe_allow_html=True)

if not model_loaded:
    st.error(
        "⚠️ Model files not found. Run `pipeline.py` first to generate "
        "`champion_model.pkl` and `scaler.pkl`."
    )
    st.stop()

# ── Inputs ─────────────────────────────────────────────────────────
st.markdown('<div class="section-label">🏗️  Property Details</div>',
            unsafe_allow_html=True)

col1, col2 = st.columns(2)

with col1:
    area_sqft = st.slider(
        "Area (sqft)",
        min_value=500, max_value=3000,
        value=1500, step=50,
        help="Total floor area of the house"
    )
    age_years = st.slider(
        "Age of House (years)",
        min_value=0, max_value=55,
        value=15, step=1,
        help="How old the house is"
    )
    garage = st.selectbox(
        "Garage",
        options=[1, 0],
        format_func=lambda x: "Yes ✅" if x == 1 else "No ❌",
        help="Does the property have a garage?"
    )

with col2:
    rooms = st.slider(
        "Number of Rooms",
        min_value=1, max_value=8,
        value=4, step=1,
        help="Total number of rooms"
    )
    dist_city_km = st.slider(
        "Distance from City (km)",
        min_value=0.5, max_value=20.5,
        value=8.0, step=0.5,
        help="Distance from city centre in kilometres"
    )

# ── Feature engineering (must match pipeline.py exactly) ───────────
log_area   = np.log1p(area_sqft)

if age_years <= 10:
    age_bucket = 0     # new
elif age_years <= 25:
    age_bucket = 1     # mid
else:
    age_bucket = 2     # old

# ── Predict ────────────────────────────────────────────────────────
if st.button("Predict Price →"):
    sample = pd.DataFrame([{
        "area_sqft"   : area_sqft,
        "rooms"       : rooms,
        "age_years"   : age_years,
        "dist_city_km": dist_city_km,
        "garage"      : garage,
        "log_area"    : log_area,
        "age_bucket"  : age_bucket,
    }])[FEATURE_COLS]

    scaled = scaler.transform(sample)
    price  = model.predict(scaled)[0]

    # ── Rough confidence band (±1 MAE from test) ───────────────────
    mae = 12_880
    low  = price - mae
    high = price + mae

    st.markdown(f"""
    <div class="result-card">
        <div class="result-label">Estimated Market Value</div>
        <div class="result-price">${price:,.0f}</div>
        <div class="result-meta">
            Confidence range &nbsp;·&nbsp; ${low:,.0f} – ${high:,.0f}
        </div>
        <div class="metric-row">
            <div class="metric-pill">Model &nbsp;·&nbsp; Linear Regression</div>
            <div class="metric-pill">R² &nbsp;·&nbsp; 0.6749</div>
            <div class="metric-pill">RMSE &nbsp;·&nbsp; $16,248</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Feature breakdown ──────────────────────────────────────────
    st.markdown('<div class="section-label">📊 Input Summary</div>',
                unsafe_allow_html=True)

    summary_df = pd.DataFrame({
        "Feature"   : ["Area (sqft)", "Rooms", "Age (yrs)",
                        "Dist from city (km)", "Garage", "log(area)", "Age bucket"],
        "Value"     : [area_sqft, rooms, age_years,
                       dist_city_km, "Yes" if garage else "No",
                       f"{log_area:.3f}",
                       ["New (<10yr)", "Mid (10-25yr)", "Old (>25yr)"][age_bucket]],
        "Type"      : ["Original", "Original", "Original",
                       "Original", "Original", "Engineered", "Engineered"],
    })
    st.dataframe(summary_df, use_container_width=True, hide_index=True)

# ── Model info box ─────────────────────────────────────────────────
st.markdown("""
<div class="info-box">
    <b>How this works</b><br>
    The model was trained on 745 cleaned house records. It uses 7 features —
    5 original and 2 engineered (<b>log_area</b>, <b>age_bucket</b>).
    Feature engineering ensures the right-skewed area distribution is handled
    before the linear model sees it.
    <br><br>
    <b>Top price drivers (from coefficients):</b><br>
    📈 area_sqft (+$11,939/sqft) &nbsp;·&nbsp;
    📉 dist_city_km (−$11,049/km) &nbsp;·&nbsp;
    📉 age_years (−$10,538/yr) &nbsp;·&nbsp;
    📈 garage (+$6,291)
</div>
""", unsafe_allow_html=True)
